### ISSUE TITLE
Error 0x00405d70

### ISSUE THREAD

**Issue by gxarmanis** [manuelruder/artistic-videos#17]
Hello! First of all congratulations for your amazing work! I am a new ubuntu user and i am interested in NN's so i thought of running your code with default parameters. As you may see from the attached screenshot after few hours of computing the optical flow i face the specific issue. I do not know what else i can do as you may see from folder screenshot every file is there. I would appreciate if you could help me further on this matter.

Thank you very much!
George.

Issue Screenshot:
![issue](https://cloud.githubusercontent.com/assets/20702845/17406476/31ca99d4-5a6c-11e6-9ec1-f7b7cbc73af1.png)

Folder Screenshot:
![folder](https://cloud.githubusercontent.com/assets/20702845/17406487/3b0c5398-5a6c-11e6-94ee-c562ad6e58ce.png)

**Comment by manuelruder** [comment]
It doesn't find "artistic_video.lua" because it's probably in a different directory than the script you are trying to execute. Just copy all the files from this repositories into the same directory as the script "stylizeVideo.sh". This repository is not supposed to be installed anywhere. Just keep all the files together (in the same directory).
Then you can run "stylizeVideo.sh" again. If you didn't delete anything, the script should recognize the already existing optical flow files and just continue with the stylization.

**Comment by gxarmanis** [comment]
Thank you very much for your help, it worked!
