### ISSUE TITLE
-continue_with option

### ISSUE THREAD

**Issue by filmo** [manuelruder/artistic-videos#8]
If a render session get interrupted, does this option allow us to restart at the 'next' frame and maintain the previous style continuity? I didn't see it referenced in the documentation other that what is in the artisitic_video.lua file

I've noticed that different runs of the same video and style frame result in different initial frames. (probably due to random initialization).

I'm trying to figure out if it's possible to safely interrupt a long render without creating a glitch between frames and what settings would need to be set either during the initial run so as to preserve the start state and/or later during a resumption. 

Thank you for your help.

**Comment by manuelruder** [comment]
Exactly, with the option `continue_with` you can continue at the 'next' frame as if you had never interrupted it.

There is also a `seed` option. With that, you can always start with the same random image at the beginning.

**Comment by filmo** [comment]
I must have done something wrong. 

I had rendered frames 1 to 35.

Should I have set -continue_with to 35 or 36? (in order to render frame 36 as the next frame upon resumption)

More importantly, would I have needed to set the -seed on the first run to some particular number for this to work? In other words, in order for -continue_with to work correctly, must -seed be set during the initial run as well? (I didn't set it on frames 1 to 35, so suspect that it is now 'lost' if I want to continue) ??

Thanks for the quick response.

**Comment by manuelruder** [comment]
You have to set  -continue_with to 36 in that case. No, it is not required to use a custom seed value in order to use the -continue_with parameter. The seed value is only needed to initialize the first frame. After that, frames are initialized with information from the previous frames, therefore it doesn't matter what seed value you have chosen or if you have set a custom seed value at all.

But a seed value may be help to evaluate the effect of different parameter settings, because it grantees that the algorithm to always starts from the same random initialization in the beginning.

**Comment by filmo** [comment]
Great! Thanks for the info.

**Comment by ProGamerGov** [comment]
@manuelruder How does the `-continue_with` parameter in `artistic_video.lua` differ from the `-continue_with_pass` parameter in `artistic_video_multiPass.lua`? 

Wouldn't it make sense for `artistic_video_multiPass.lua` to have the `-continue_with` parameter as well?
