### ISSUE TITLE
EpicFlow instead of DeepFlow

### ISSUE THREAD

**Issue by filmo** [manuelruder/artistic-videos#9]
Have you experimented with EpicFlow as the optical flow engine? If so would you recommend it over DeepFlow. (faster? better? etc.)

I've also noticed that for large video sizes (960 x 540) DeepFlow is very slow (~22 seconds per frame). Unfortunately it appears to be single threaded unlike DeepMatch which is multi-threaded and runs at about 5 seconds for a forward/backward match per frame on my set up. I'm using the -R 2 setting on DeepMatch to cut the number of matches down, but would still like to find a way to reduce the DeepFlow computation time.

I'm currently working on a shell script to create multiple DeepFlow processes to keep all my cores occupied, but if you've found a work around that already solves this problem let me know. I didn't see a multi-threaded version of DeepFlow on the author's site. 

Thanks

**Comment by manuelruder** [comment]
Another workaround is to run the optical flow algorithm in parallel with the actual video style transfer script. Because stylizing one frame usually needs more time than computing the optical flow, the optical flow will always be finished once it's needed.

EpicFlow isn't faster than DeepFlow. In fact it's even more complex so it might be a little bit slower. In our paper, we have tried both DeepFlow and EpicFlow and the DeepFlow results are better on average.

**Comment by filmo** [comment]
Thanks for the info.
